import { z } from "zod";

export const consentSchema = z.object({
  consent_documents: z.literal(
    true,
    "You must consent to sharing your documents/photos/videos",
  ),
  consent_availability: z.literal(true, "You must confirm your availability"),
  availability_date: z.string().min(1, "Please specify your availability date"),
  consent_truthful: z.literal(
    true,
    "You must confirm that all responses are truthful, written by you, and not generated by AI",
  ),
});

export type ConsentInput = z.input<typeof consentSchema>;
